demo/templatizer-test.html
Requesting review on this in order to merge with master.
=> Replacing content with slot. Refs #15934

cosmoz-omnitable.js
- some small improvements found while creating tests 
- verifyColumnSetup() created for testing override purposes
=> Test Preparation & small improvments

.eslintrc.json, cosmoz-omnitable-column-time.html, cosmoz-omnitable-columns.html, demo/editable-demo.html, demo/full-demo.html, demo/table-demo-behavior.html
Please merge https://github.com/Neovici/cosmoz-omnitable/pull/38 first
=> Time Column

.gitignore, cosmoz-omnitable-styles.html, cosmoz-omnitable.html, cosmoz-omnitable.js
See issue https://github.com/Neovici/cosmoz-omnitable/issues/10
Please merge https://github.com/Neovici/cosmoz-grouped-list/pull/9 first!
=> Add support for highlighted items [issue-10]

docs/documentation.md
Adding name attribute to documentation.
=> Name attribute in documentation

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-behavior.html, cosmoz-omnitable-column-boolean.html, cosmoz-omnitable-column-date-behavior.html, cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-number.html, cosmoz-omnitable-column-time.html, demo/editable-demo.html
See https://github.com/Neovici/cosmoz-omnitable/issues/35
- Columns now fire an event if items change and editable-demo shows the change.
- Fixed editing in some columns.
=> Editable columns fix & demo [issue-35]

.eslintrc.json, bower.json, cosmoz-omnitable-column-boolean.html, cosmoz-omnitable-column-date-behavior.html, cosmoz-omnitable-column-time.html, cosmoz-omnitable.html, cosmoz-omnitable.js, demo/hash-param.html, demo/helpers/hash-param-template.html, demo/helpers/x-page.html, demo/index.html, test/hash-param.html, test/index.html
Persist filtering in URL:
* Added groupOn, sortOn, descending to hash-param
* Added demo with cosmoz-page-router
fixes #61
=> Persist filtering in URL

cosmoz-omnitable.js
Fix regexp for matching column name
=> Fix regexp for matching column name

bower.json, cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-behavior.html, cosmoz-omnitable.html, cosmoz-omnitable.js, import-nullxlsx.html, test/index.html, test/xlsx-export.html
Added XLSX export/download
fixes #8
=> XLSX export/download

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-autocomplete.html, cosmoz-omnitable-column-behavior.html, cosmoz-omnitable-column-boolean.html, cosmoz-omnitable-column-list.html, cosmoz-omnitable-repeater-behavior.html, cosmoz-omnitable-templatizer.html, cosmoz-omnitable.html, cosmoz-omnitable.js, demo/ajax-demo.html, demo/custom-template-demo.html, demo/detach_test.html, demo/editable-demo.html, demo/empty-demo.html, demo/filter-demo.html, demo/full-demo.html, demo/group-on-demo.html, demo/hash-param.html, demo/helpers/hash-param-template.html, demo/helpers/x-page.html, demo/multi-filter-demo.html, demo/sort-demo.html, demo/styling.html, package.json, test/basic.html, yarn.lock
fixes #71 
The groupOnColumn should be excluded from filters.
=> Changing groupOn should not overwrite visibleColumns

cosmoz-omnitable-column-autocomplete.html
Fix toXlsxValue in autocomplete column
toXlsxValue uses textProperty
fixes #79
=> Fix toXlsxValue in autocomplete column

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-autocomplete.html, cosmoz-omnitable-column-behavior.html, cosmoz-omnitable-column-boolean.html, cosmoz-omnitable-column-date-behavior.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-list.html, cosmoz-omnitable-column-number.html, cosmoz-omnitable-column-time.html, cosmoz-omnitable-header-row.html, cosmoz-omnitable-item-expand.html, cosmoz-omnitable-item-row.html
Added _getDefaultFilter and CSS for hidden attribute in repeaters
Added _getDefaultFilter for date columns
Filter for date columns is not computed and readonly anymore
Check for null filter.start & filter.end in date columns getFilterFn
fixes #69
=> Add _getDefaultFilter and CSS for hidden attribute in repeaters

cosmoz-omnitable.html, cosmoz-omnitable.js
=> Sort groups descending

analysis.json, cosmoz-omnitable-column-list.html, cosmoz-omnitable.html, cosmoz-omnitable.js, test/hash-param.html
Integrate cosmoz-page-location changes
To be merge after Neovici/cosmoz-page-router#19 is merged.
=> Integrate cosmoz-page-location changes

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-behavior.html, cosmoz-omnitable-column-number.html, cosmoz-omnitable-column-range-behavior.html, cosmoz-omnitable-column.html, cosmoz-omnitable.js
=> Refactor amount and number columns

cosmoz-omnitable-column-range-behavior.html
Add default for `_limit` quick-fix
=> Add default for limit

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-date-behavior.html, cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-number.html, cosmoz-omnitable-column-range-behavior.html, cosmoz-omnitable-column-time.html
Added serialize and deserialize for filter in date columns so that filter always contains Date objects.
For time column filter is string.
=> Filter for date and datetime should always be a Date

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-behavior.html, cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-number.html, cosmoz-omnitable-column-range-behavior.html, cosmoz-omnitable-column-time.html, cosmoz-omnitable-styles.html
Add clear icon to `resetFilter` in date, datetime, time, amount and number
Relates to #26
=> Add clear icon to resetFilter in date, datetime, time, amount and number

cosmoz-omnitable-column-range-behavior.html
Handle null or undefined in serializeFilter
=> Handle null or undefined in serializeFilter

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-number.html, cosmoz-omnitable-column-range-behavior.html, cosmoz-omnitable-column-time.html, cosmoz-omnitable-styles.html
- Handle null, undefined in _serializeFilter
-  Clear filter button should always be hidden if filter is null or undefined
=> Range columns tweaks

cosmoz-omnitable.js, test/hash-param.html
Update params from route once on init
fixes #101
=> Update params from route once on init

test/hash-param.html
Update route hash tests
fixes #101
=> Update route hash tests

cosmoz-omnitable-column-range-behavior.html
Handle `undefined`/`null` filter in `computeFilterText`
=> Handle undefined/null filter in computeFilterText

cosmoz-omnitable.js
=> Expose omnitable visibility

cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-range-behavior.html
fixes Neovici/cosmoz-omnitable/issues/118
=> Filtering date fix

cosmoz-omnitable.js, test/basic.html, test/hash-param.html
=> ensure single _updateColumns() call

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-date-behavior.html, cosmoz-omnitable-column-range-behavior.html, cosmoz-omnitable-column-time.html
Added range columns fixes and documentation
Extracted from #108 
fixes #111
=> Range columns fixes and docs

cosmoz-omnitable.html, test/xlsx-export.html
fixes: second click does not download file. https://github.com/Neovici/cosmoz-omnitable/issues/123
=> Used on-click instead of on-action and click tests

cosmoz-omnitable-column-range-behavior.html
Refactor computeLimit to use min/max
fixes #127
=> Refactor computeLimit to use min/max

cosmoz-omnitable-column-date-behavior.html, cosmoz-omnitable-column-datetime.html, package.json, test/index.html, test/range-date.html, test/range.html
Add tests for range based columns.
fixes #104
=> Range columns tests

.eslintrc.json, cosmoz-omnitable-column-amount.html, cosmoz-omnitable.js, test/basic.html, test/hash-param.html, test/range-date.html, test/range.html
PR #114 had problems with tests.
Fixed tests and related misc issues. 
The main problem was that a resize was needed in order to make sure everything is correct when checking if params from hash are reflected in omnitable properties.
=> Render on visible (with tests)

bower.json, cosmoz-omnitable-column-datetime.html
depends on: https://github.com/Neovici/cosmoz-datetime-input/issues/2
=> Replaced JaySunSyn/datetime-local with Neovici/cosmoz-datetime-input

cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-range-behavior.html, cosmoz-omnitable-column-time.html, test/xlsx-export.html
fixes: https://github.com/Neovici/cosmoz-omnitable/issues/133
=> toXlsxValue date to local time

test/xlsx-export.html
Vancouver Canada, Lisbon Portugal
=> toXlsx tests for date with different timezones

cosmoz-omnitable-column-autocomplete.html, cosmoz-omnitable-column-behavior.html, cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-time.html, cosmoz-omnitable-column.html, cosmoz-omnitable-item-row.html
[fix] Force Chrome to properly size elements with text overflow.
[fix] Add support for minimum width
fixes #145
=> Sizing fixes

cosmoz-omnitable.js
=> Fix columns missing values property on render visible

cosmoz-omnitable-column-autocomplete.html
fixes https://github.com/Neovici/cosmoz-omnitable/issues/113
depends on https://github.com/Neovici/paper-autocomplete-chips/pull/12
=> expose focused property for column autocomplete

cosmoz-omnitable.html, cosmoz-omnitable.js, test/fit-dropdowns.html, test/index.html
On attach set `paperDropdownMenu.$.menuButton.$.dropdown.fitInto` to `this`
Fixes #58
=> Fit dropdown into omnitable

.eslintignore, .gitignore, .travis.yml, package.json, polymer.json, wct.conf.json, yarn.lock
Add test code coverage with patched web-component-tester-istanbul
Send code coverage to codeclimate
=> Add test code coverage

analysis.json, cosmoz-omnitable-column-amount.html, demo/helpers/x-page.html, test/range.html, yarn.lock
1. Rates object, getComparableValue updated ( sorting and filtering are now based on amount value ).  added tests with rates.
2. Configurable 'currency' property used in filters menu, added test.
3. Auto-detect 'currency' property if not configured.
4. If 'autodetect' property is true then 'currency' with be the currency with the highest occurrence ( implemented in function _valuesChanged ). added tests.
5. formatters optimization: when data changes get only formatters that are not already created from the old set of values.
6. Seems there is still an issue, in the input fields, min and max values are not converted to the detected currency.
fixes https://github.com/Neovici/cosmoz-omnitable/issues/24
=> Currency management in column amount

cosmoz-omnitable-column-boolean.html, cosmoz-omnitable-column-list-horizontal.html, cosmoz-omnitable-column-list.html, test/basic.html, test/boolean.html, test/index.html, test/list.html
Issue to fix https://github.com/Neovici/cosmoz-omnitable/issues/164
Column boolean code optimizations.
Tests: boolean, column, list, horizontal list.
=> Tests for boolean, column, list, horizontal list. small code optimizations.

cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-range-behavior.html, test/range.html
Improve range columns limiting
=> Improve range columns limiting

cosmoz-omnitable-repeater-behavior.html, cosmoz-omnitable-templatizer.html
=> Memory leak fixes

cosmoz-omnitable-styles.html
primary link color with shadow dom. related issue: https://github.com/Neovici/cosmoz-frontend/issues/171
=> primary link color

cosmoz-omnitable.js
Also correct and extend doc for `sorter()`
=> Reuse compareFunction for sorting

cosmoz-omnitable.js
set filteredItems to an empty Array by default
fixes #173
=> set filteredItems to an empty Array by default

cosmoz-omnitable.js
removeItems
- make sure to return all successful removals instead of last try
es6
- es6 class style method declarations
- const/let > var
-- + multi-const
- arrow functions
minor doc update
minor readability touches
=> removeItems fix, es6 updates

.travis.yml, cosmoz-omnitable-item.html, cosmoz-omnitable.html, demo/group-on-demo.html, demo/helpers/cosmoz-translations.html, demo/helpers/x-page.html, demo/sort-demo.html, test/group.html, test/index.html, test/range.html, yarn.lock
Group, Sort demo fixes.
fixes #184
Tests:
Group and Sort 'cosmoz-omnitable-column' ( name='id' ).
Group and Sort 'cosmoz-omnitable-column-boolean' (name='bool').
GroupOn 'amount' updates groupOnColumn property to the corresponding column.
=> Group, sort demo fixes; Group, sort tests for column, boolean, amount columns

test/basic.html, test/fit-dropdowns.html, test/range-date.html
#193
Unit tests for coverage (methods handle null, undefined, test returned values..)
cosmoz-omnitable-column-autocomplete.html
cosmoz-omnitable-column-behavior.html
cosmoz-omnitable-column-datetime.html.html
=> More tests for better coverage

cosmoz-omnitable-column-boolean.html, test/boolean.html
fixes #196 
1. Replicate issue. (in demo hash-param.html select yes as Boolean value then refresh the page)
2. Serialize as strings, deserialize strings to boolean. 
3. More tests to cover the new functions.
4. Ask for reviews.
=> Boolean column _serializeFilter, _deserializeFilter. And more tests.

cosmoz-omnitable.html, cosmoz-omnitable.js
fixes #189
depends on https://github.com/Neovici/cosmoz-grouped-list/pull/19
1. Build failed on travis-ci because the PR mentioned above is not merged yet in cosmoz-grouped-list.
2. Tests are passing  on localhost with 'cosmoz-grouped-list' branch 'plumelo:feature/NEOV-230-refactor-cosmoz-templatize' using 'bower link'.
3. Use class instead of type. Done.
4. Verify the functionality in demo and the result of tests. Done.
=> cosmoz-grouped-list templates update.

cosmoz-omnitable-column-behavior.html, cosmoz-omnitable-repeater-behavior.html, cosmoz-omnitable.js, yarn.lock
Re-render template instances on column editable change.
fixes #202
=> Re-render template instances on column editable change

cosmoz-omnitable-column-range-behavior.html, test/range.html
=> Fixes invalid limit when external value is true and passed values are an empty array

cosmoz-omnitable-column-number.html, test/range.html
=> Fixes number column getComparableValue not returning a number

bower.json, test/basic.html
Update cosmoz-grouped-list to 2.0.1
=> Update cosmoz-grouped-list to 2.0.1

cosmoz-omnitable-column-boolean.html, test/boolean.html
Boolean column, fix to follow column data updates after table has been rendered, issue is #215 and #19683.
=> 215 - Boolean column, fix to follow column data updates after table has been rendered

cosmoz-omnitable.js
Fixes computing _dataIsValid on subpath changes
fixes #224
=> Fixes computing _dataIsValid on subpath changes

cosmoz-omnitable-column-list.html
cosmoz-omnitable-column-list 
* added null check for filter in filterChanged
=> NOREF - cosmoz-omnitable-column-list - added null check for filter in filterChanged

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-templatizer.html, test/group.html, test/range.html
Converting files to class-style.
Testing: Test the `cosmoz-omnitable-column-amount column` where applicable, it should be as before.
Issue is #246.
=> 246 - Converting files to class-style

demo/helpers/x-page.html, demo/table-demo-behavior.html
=> x-page/demo-behavior - Add list of objects column

cosmoz-omnitable-column-list-data.html, cosmoz-omnitable-item-expand.html, cosmoz-omnitable-repeater-mixin.html, cosmoz-omnitable-templatizer.html, cosmoz-omnitable.html, cosmoz-omnitable.js, test/basic.html, test/group.html, test/hash-param.html, test/helpers/utils.js, test/range-date.html, test/range.html, test/xlsx-export.html
* Upgrade to class-based element
* remove use of Polymer.dom
* use Polymer.Debouncer instead of this.debounce
* use addEventListener/removeEventListener instead of listeners
* use FlattenedNodesObserver instead of Polymer.dom().observe
@megheaiulian @nomego
=> Upgrade <cosmoz-omnitable> to Polymer 2.x

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-autocomplete.html, cosmoz-omnitable-column-boolean.html, cosmoz-omnitable-column-date-mixin.html, cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-list-data.html, cosmoz-omnitable-column-list-horizontal.html, cosmoz-omnitable-column-list-mixin.html, cosmoz-omnitable-column-list.html, cosmoz-omnitable-column-mixin.html, cosmoz-omnitable-column-number.html, cosmoz-omnitable-column-range-mixin.html, cosmoz-omnitable-column-time.html, cosmoz-omnitable-column.html, cosmoz-omnitable-group-row.html, cosmoz-omnitable-header-row.html, cosmoz-omnitable-item-expand-line.html, cosmoz-omnitable-item-expand.html, cosmoz-omnitable-item-row.html, cosmoz-omnitable-item.html, cosmoz-omnitable-repeater-mixin.html, cosmoz-omnitable-styles.html, cosmoz-omnitable-templatizer.html, cosmoz-omnitable.html
I have updated each file with only the required imports.
Fixes #263
=> (patch) Update Polymer 2.x imports

.travis.yml
Adding Sauce Labs configuration.
No issue.
=> Adding Sauce Labs configuration

cosmoz-omnitable-item-expand-line.html
=> Folded columns styling

cosmoz-omnitable-column-list-data.html, cosmoz-omnitable.js, demo/editable-demo.html, demo/filter-demo.html, demo/multi-filter-column.html, demo/multi-filter-demo.html, demo/styling.html
Demo, converting views to class-style.
Also adding back translation functions since the translation behavior needs to be converted for those to be removed.
Testing, `yarn install; yarn start`, add `demo/` to the address.
=> Demo, converting views to class-style

demo/ajax-demo.html, demo/detach_test.html, demo/editable-demo.html, demo/empty-demo.html, demo/filter-demo.html, demo/group-on-demo.html, demo/helpers/cosmoz-translations.html, demo/helpers/x-page.html, demo/index.html, demo/multi-filter-demo.html, demo/sort-demo.html, demo/styling.html, test/group.html, test/integration/templatize.html
Demo, Test, converting views to class-style.
Testing, run `yarn install; yarn start`, add `demo/` to the address. Also run tests.
=> Demo, Test, converting views to class-style

cosmoz-omnitable-column-datetime.js, cosmoz-omnitable-column-list-data.js, cosmoz-omnitable.js, demo/helpers/x-page.js
https://github.com/Neovici/cosmoz-frontend/issues/1314
=> (patch) modulizer erroneously escaped `attr$=` to `attr\$=`

cosmoz-omnitable-column-amount.js, cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-boolean.js, cosmoz-omnitable-column-date.js, cosmoz-omnitable-column-datetime.js, cosmoz-omnitable-column-list-horizontal.js, cosmoz-omnitable-column-list.js, cosmoz-omnitable-column-number.js, cosmoz-omnitable-column-time.js, cosmoz-omnitable-column.js, cosmoz-omnitable.js
This results in a minor performance boost.
https://polymer-library.polymer-project.org/3.0/docs/devguide/dom-template#strip-whitespace
=> (patch) use strip-whitespace to reduce the node count

cosmoz-omnitable-column-amount.js, cosmoz-omnitable-column-date.js, cosmoz-omnitable-column-number.js, cosmoz-omnitable-column-range-mixin.js, selenium-overrides.js, test/index.html, test/integration/column-number.html, test/range.html
=> (patch) Range column behavior update (amount, number)

cosmoz-omnitable-column-mixin.js, cosmoz-omnitable-column.js, test/basic.html, test/index.html
Now filtering starts when user presses enter, blur occurs or 1 second passes without additional user text input.
Unsure if this can make it to the circuit release since alpha has started. Leaving project blank
Refs https://github.com/Neovici/cosmoz-omnitable/issues/60
=> Changes when filtering is done in an default textinput column

package.json
=> Updating to version 3.0.11

cosmoz-omnitable-column.js, test/hash-param.html
Fixes Neovici/cosmoz-frontend#1586
=> fix(filter): free text filters don't persist

cosmoz-omnitable.js, test/xlsx-export.html
https://neovici.slack.com/archives/DGX65MV34/p1571303877323000
=> Cleanup private interface

cosmoz-omnitable.js, test/xlsx-export.html, wct.conf.json
when data is an empty array
Fixes #328
=> fix: `all selected` checkbox is checked

cosmoz-omnitable-column-autocomplete.js
=> fix: make sure spinner in autocomplete is properly hidden

cosmoz-omnitable.js, package-lock.json, package.json
=> feat(selection): support cosmoz-grouped-list compareItemsFn

cosmoz-omnitable-styles.js
Style, adding item-row-min-height custom property.
Testing, check line height and make sure it has not changed from the default ~25px.
Issue is RM:22270.
=> 22270 - Style, adding item-row-min-height custom property

.github/workflows/workflow.yml
Re https://github.com/Neovici/cosmoz-frontend/issues/1793
=> ci: use correct actions/checkout version

test/range.html, test/xlsx-export.html
Fixes https://neovici.slack.com/archives/C6LJQMJFM/p1582718262025000?thread_ts=1582715823.020600&cid=C6LJQMJFM
=> test: auto-detected locale differences cause tests to fail

cosmoz-omnitable-column-boolean.js, test/boolean.html
As requested in https://github.com/Neovici/cosmoz-omnitable/pull/335#pullrequestreview-365495673.
#315.
=> fix: rework boolean column #315

cosmoz-omnitable.js
Adds a slot for additional download menu actions/items.
=> feat: adds download-menu slot

cosmoz-omnitable-styles.js
Style paper-button in download-menu slot
=> fix: style paper-button in download-menu slot

cosmoz-omnitable-item-row.js
=> fix: adjustColumns handles empty cells

package-lock.json, package.json
upgrade to cosmoz-page-router@^6.0.0
=> feat: upgrade to cosmoz-page-router@^6.0.0

package.json
Re https://github.com/Neovici/cosmoz-frontend/issues/2005
```
npm pack
npm notice
npm notice 📦  @neovici/cosmoz-omnitable@3.4.0
npm notice === Tarball Contents ===
npm notice 11.3kB LICENSE
npm notice 1.3kB  ui-helpers/cosmoz-clear-button.js
npm notice 9.8kB  cosmoz-omnitable-column-amount.js
npm notice 3.9kB  cosmoz-omnitable-column-autocomplete.js
npm notice 8.7kB  cosmoz-omnitable-column-boolean.js
npm notice 5.4kB  cosmoz-omnitable-column-date-mixin.js
npm notice 3.3kB  cosmoz-omnitable-column-date.js
npm notice 3.7kB  cosmoz-omnitable-column-datetime.js
npm notice 2.7kB  cosmoz-omnitable-column-list-data.js
npm notice 3.4kB  cosmoz-omnitable-column-list-horizontal.js
npm notice 847B   cosmoz-omnitable-column-list-mixin.js
npm notice 3.6kB  cosmoz-omnitable-column-list.js
npm notice …
```
=> chore(pkg): include only relevant files in package archive

cosmoz-omnitable-column-list.js, cosmoz-omnitable-group-row.js, cosmoz-omnitable-styles.js
Testing, check that the group on for the list column groups as it should.
Note, this does not cover the design error for the and ... more links when using cell templates.
If you know how to solve that please tell me.
Ran tests locally and they passed.
Issue is RM:23196.
=> feat: list column value property groupon

cosmoz-omnitable.js
=> fix: suppress scroll reset on item replace

cosmoz-omnitable-styles.js, cosmoz-omnitable.js
Adding empty set message slot.
RM:23679.
=> fix: cosmoz-omnitable, adding empty set message slot #23679

test/basic.test.js
=> chore(test): fix flaky adjust columns test

cosmoz-omnitable.js, get-effective-children-legacy-mixin.js
Broken in 3254986971a45d696e55ec1e9c4bcba7f05b3c90
=> fix(update-columns): slotted columns are not displayed

cosmoz-omnitable-column-list-mixin.js
Adds `emptyLabel` and `emptyValue` to list columns allowing filtering for empty values.
Fixes #406
=> feat: adds emptyLabel and emptyValue to list columns

cosmoz-omnitable.js
=> feat: expose bottom-bar info slot

cosmoz-omnitable-column-mixin.js, cosmoz-omnitable-header-row.js, cosmoz-omnitable-item-expand.js, cosmoz-omnitable-item-row.js, cosmoz-omnitable-repeater-mixin.js, cosmoz-omnitable.js, demo/editable-demo.html, demo/helpers/x-page.js, test/basic.test.js
=> feat: lit render functions support

cosmoz-omnitable-column-mixin.js, cosmoz-omnitable-group-row.js, test/basic.test.js
=> feat: custom render group function

cosmoz-omnitable-item-expand.js
Re https://neovici.slack.com/archives/C0APSNTPB/p1616584046026800
=> fix: expanded rows don't update size after column changes

cosmoz-omnitable-header-row.js, cosmoz-omnitable.js, lib/use-force-render.js, lib/use-render-on-column-updates.js, package.json, test/basic.test.js, test/integration/column-number.test.js, test/range.test.js
Re https://github.com/Neovici/cosmoz-frontend/issues/3282
=> fix: migrate header-row to haunted

cosmoz-omnitable.js, package-lock.json, package.json
Implements multi-select:
- ctrl -> select only this item/group
- shift + click -> toggle a range from last interacted
fixes #177
=> feat: implement multi-select

cosmoz-omnitable-column-boolean.js
Remove label for edit cell on boolean columns.
=> fix(cosmoz-omnitable-column-boolean): remove label for edit cell

cosmoz-omnitable-item-expand.js, cosmoz-omnitable-styles.js, cosmoz-omnitable.js, lib/use-fast-layout.js
Also included fix for rendering issues when resizing or scrolling with expanded rows.
Fixes #432
=> fix: expand columns arrow always shows up when table is grouped

cosmoz-omnitable-item-row.js
=> fix: selections overlap columns when double clicking

cosmoz-omnitable-column-mixin.js, cosmoz-omnitable-header-row.js, cosmoz-omnitable-styles.js, cosmoz-omnitable.js, demo/helpers/x-page.js, lib/cosmoz-omnitable-resize-nub.js, lib/use-fast-layout.js
Fixes #440 
This is a prototype which we can test out in alpha, by adding `resizable` to some omnitables.
=> feat: resizable headers prototype

cosmoz-omnitable-item-row.js
=> fix: rows are misaligned when cells have different heights

cosmoz-omnitable.js
=> fix: typo in `Sort on`

cosmoz-omnitable-column-date.js
Hide dropdown icon when using the date column.
=> fix(date): hide dropdown icon

cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-list-mixin.js, package-lock.json, package.json, test/autocomplete.test.js
Fixes https://github.com/Neovici/cosmoz-omnitable/issues/435
=> feat: values as function

cosmoz-omnitable-column-mixin.js, cosmoz-omnitable-header-row.js, cosmoz-omnitable-item-expand.js, cosmoz-omnitable-item-row.js, cosmoz-omnitable.js, lib/compute-layout.js, lib/cosmoz-omnitable-resize-nub.js, lib/layout.js, lib/use-canvas-width.js, lib/use-fast-layout.js, lib/use-layout-config.js, lib/use-layout.js, lib/use-omnitable.js, lib/use-resizable-columns.js, lib/use-track-size.js, lib/use-tween-array.js, test/basic.test.js, test/layout.test.js
Also included:
* deprecated visibleColumns and disabledColumns
* fix editable attribute being set on the cells, even though column is not editable
* fix for expand rows not resizing when columns are collapsed/expanded
=> Finish resizable columns implementation

lib/use-resizable-columns.js
=> fix(resizable-columns): you can't resize the last column anymore

lib/cosmoz-omnitable-settings.js, package-lock.json, package.json
Toggle settings by clicking the button.
=> fix(settings): toggle settings Toggle settings by clicking the button

lib/compute-layout.js
=> fix(layout): error when columns are hidden conditionally

cosmoz-omnitable-column-range-mixin.js
Filter out undefined values when a range (min or max) is set
=> fix(range-column): filter out undefined values

cosmoz-omnitable-column-amount.js, cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-date.js, cosmoz-omnitable-column-datetime.js, cosmoz-omnitable-column-list-mixin.js, cosmoz-omnitable-column-number.js, cosmoz-omnitable-column-time.js, lib/use-dom-columns.js, lib/utils-data.js
Changes required for integrating with FE and omnitable-treenode-column
=> More integration fixes

lib/utils-data.js
Handles non Array data in `valuesFrom`.
=> fix(valuesFrom): handle non Array

lib/cosmoz-omnitable-settings.js, package-lock.json, package.json
Improve design of omnitable settings.
=> feat: improve design of omnitable settings

cosmoz-omnitable-column-mixin.js, lib/use-hash-state.js, lib/use-processed-items.js, test/basic.test.js
=> fix(default-column): workaround for double-encoded filters

cosmoz-omnitable-styles.js, cosmoz-omnitable.js, package-lock.json
=> feat: add controls slot

lib/utils-date.js
=> fix(column-date): parse dates as UTC

test/generic-sorter.test.js, test/memoize.test.js, test/utils-date.test.js
@basilgood you can base your work on this.
=> test: more unit tests

package-lock.json, package.json
=> fix(deps): update cosmoz-page-router

lib/use-dom-columns.js
Re https://neovici.slack.com/archives/C6LJQMJFM/p1642425651009800
=> fix(use-dom-columns): changes to enabled columns are ignored

cosmoz-omnitable-styles.js, package-lock.json, package.json
=> feat(deps): upgrade cosmoz-bottom-bar

package-lock.json, package.json
upgrade cosmoz-autocomplete v3
=> feat(cosmoz-autocomplete): upgrade

cosmoz-omnitable-header-row.js, cosmoz-omnitable.js, package-lock.json, package.json
Fixes clear button for sort/group not resetting sortOn/groupOn.
Cleans up header-row
Updates & cleans up some deps
related to #502
=> fix(cosmoz-omnitable): clear sort & group

cosmoz-omnitable-header-row.js, cosmoz-omnitable-styles.js, cosmoz-omnitable.js, lib/cosmoz-omnitable-settings.js, lib/cosmoz-omnitable-sort.js, package-lock.json
Adds sort handle to omnitable header rows that allows to quickly toggle sort on a column.
Example:
=> feat(omnitable): sort headers

cosmoz-omnitable-styles.js
Make inputs fill the header column when there are a few columns.
=> fix(sort): correct sizing with less columns

cosmoz-omnitable-styles.js
Show sort icon with arrrow pointing up when ascending.
=> fix(sort): flip icon

lib/cosmoz-omnitable-group.js, lib/cosmoz-omnitable-settings.js, lib/use-sort-and-group-options.js
Adds group dropdown to omnitable settings.
=> feat(group): add group to settings

package-lock.json, package.json
=> feat: update cosmoz-page-router

cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-list.js
Adds valueProperty to autocomplete in list column.
Disallow flexing spinner in autocomplete.
=> fix(column-list): add valueProperty to autocomplete

cosmoz-omnitable.js, lib/settings/cosmoz-omnitable-settings.js, lib/settings/normalize.js, lib/settings/use-saved-settings.js, lib/settings/use-settings-ui.js, lib/settings/use-settings.js, lib/use-fast-layout.js, lib/use-omnitable.js, lib/use-resizable-columns.js, lib/use-sort-and-group-options.js, package-lock.json
Allow settings that are not per column.
Implements saving settings for sortOn, descending, groupOn, groupOnDescending and priority is:
1. value from hash   param
2. value set on omnitable  as prop or attr
3. value from settings
=> feat(settings): misc settings

cosmoz-omnitable-styles.js, cosmoz-omnitable.js
Adds item part for styling and a click event.
=> feat(omnitable): add item part and item click event

cosmoz-omnitable.js
Handle click on itemRow correctly.
=> fix: correct itemRow click

lib/settings/normalize.js, lib/settings/use-saved-settings.js, lib/settings/use-settings.js, lib/use-omnitable.js, lib/use-sort-and-group-options.js
Fixes reseting sort and group options when reseting omnitable settings.
=> feat(sort-and-group): implement correct reset

cosmoz-omnitable-styles.js, cosmoz-omnitable.js, test/basic.test.js
Remove the footer showing sort, group and stats.
https://user-images.githubusercontent.com/1788114/190338603-064d8d11-5f66-4bf2-b941-a06036eb74ad.mp4
=> feat!: remove footer

lib/use-public-interface.js
Fixes https://neovici.slack.com/archives/C0APSNTPB/p1666767654167999?thread_ts=1666679754.010289&cid=C0APSNTPB
=> fix: sortOn and descending changes are not notified

.gitignore, cosmoz-omnitable-styles.js, cosmoz-omnitable.js, lib/render-header.js, lib/use-omnitable.js, lib/use-public-interface.js
[AB#8033](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/8033)
Connected Cosmoz PR: https://github.com/Neovici/cosmoz-frontend/pull/4764
=> feat(selectAll): hide Select All checkbox, expose selectAll and deselectAll methods

cosmoz-omnitable-header-row.js, cosmoz-omnitable-styles.js, lib/render-header.js, lib/settings/cosmoz-omnitable-settings.js, lib/settings/style.css.js
[AB#8033](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/8033)
As @megheaiulian suggested I changed the dots into button for UI settings. It's displayed only for the lists with hidden checkbox.
Screen record:
https://user-images.githubusercontent.com/48321438/198033871-cc3e3069-6e0e-485a-b985-a6c1f0cf45e4.mov
=> feat(selectAll): new layout with settings

cosmoz-omnitable-styles.js, lib/settings/style.css.js
Use same width for number chars
=> feat(number-column): use same width for number chars

lib/use-omnitable.js
[AB#8033](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/8033)
Change needed for Polymer components
=> feat(checkbox): add check needed for polymer components

lib/render-footer.js
Correctly set the placement property instead of the attribute.
=> fix(drodpown): correct placement

cosmoz-omnitable.js
Handle the `settings-id` attribute.
=> fix: handle settings-id

lib/use-public-interface.js, package-lock.json, package.json
=> fix(use-public-interface): memoize

.github/workflows/workflow.yml, cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-list.js, package-lock.json, package.json
Pass the itemRenderer property to cosmoz-autocomplete in list columns.
=> feat(list): pass item-render to cosmoz-autocomplete

lib/settings/cosmoz-omnitable-settings.js, lib/settings/use-settings-ui.js
Fixes [AB#8399](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/8399)
=> fix(settings): keep collapsed columns hidden when disabling a column

cosmoz-omnitable-column-mixin.js, test/list.test.js
This is for when users c&p something for example and an extra spacebar at the beginning an/or end sneaks in. 
Added an test ('_applySingleFilter returns true if filterString is equal to value despite extra space characters added') as well. (the rest is formatting.)
=> Applying trim for more lenient searching

lib/use-public-interface.js, package-lock.json, package.json, test/hash-param-read.test.js, test/range-amount.test.js, test/range-date.test.js, test/range-datetime.test.js, test/range-time.test.js, test/range.test.js
Fixes [AB#9731](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/9731)
=> feat(filters-changed): emit filters-changed event

cosmoz-omnitable.js, lib/use-omnitable.js, lib/use-processed-items.js
Fixes [AB#8486](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/8486)
=> feat(no-local): add support for disabling local sorting and filtering

lib/use-dom-columns.js
Needed for treenode column change [#92](https://github.com/Neovici/cosmoz-omnitable-treenode-column/pull/92)
=> feat(treenode column): passing along three new values

cosmoz-omnitable-column-list-mixin.js, lib/use-dom-columns.js
=> feat: restore column props

cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-list.js, package-lock.json, package.json
Pass textual to `cosmoz-autocomplete`,
=> feat: pass textual to cosmoz-autocomplete

cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-list-mixin.js, package-lock.json, package.json, test/basic.test.js
=> feat: upgrade autocomplete

.github/workflows/workflow.yml, package-lock.json, package.json
=> feat: upgrade to autocomplete v7

lib/render-header.js
=> feat(header): export the all part

cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-list-mixin.js, lib/invoke.js, lib/use-hash-state.js, lib/use-processed-items.js
Improve support for `emptyValue` and `emptyLabel`.
=> feat(list): better support for empty

cosmoz-omnitable-styles.js
Feature [AB#11434](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/11434) - omnitable support for a [Frontend PR](https://github.com/Neovici/cosmoz-frontend/pull/5694).
=> fix(omnitable-hover): hover color var of itemRows initialized in Omnitable

cosmoz-omnitable-styles.js, package-lock.json
Transparent fallback hover color.
=> feat: transparent fallback hover color

cosmoz-omnitable-column-list-mixin.js
Handle values being a function that returns a Promise.
=> feat(list): handle promise source

cosmoz-omnitable-column-boolean.js
small fix, just noticed it in the code
=> fix(boolean column): element name mismatch fix

lib/save-as-xlsx-action.js, package-lock.json
=> fix: update deps

lib/render-list.js, lib/use-list.js, lib/use-omnitable.js, test/__snapshots__/render-list.test.snap.js, test/render-list.test.js
Render error in omnitable based on sent in value
[AB#11960](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/11960/)
=> feat: render data error in omnitable

lib/use-tween-array.js
Updated the tweening animation loop to run only when needed.
=> fix: tween does not stop running

cosmoz-omnitable.js
Cannot configure the omnitable to sort descending.
=> fix: descending and group-on-descending are not observed

cosmoz-omnitable-styles.js, lib/cosmoz-omnitable-date-range-input.js, lib/cosmoz-omnitable-datetime-range-input.js, package-lock.json
=> feat: adjust header styles

cosmoz-omnitable-styles.js
Fixes https://neovici.slack.com/archives/C6LJQMJFM/p1709226371868849?thread_ts=1709191873.509549&cid=C6LJQMJFM
=> fix: group rows are not full width

.vscode/settings.json
=> fix(vscode-settings): change eslint setting

cosmoz-omnitable-styles.js, lib/use-list.js
=> feat(mini): adjust styles

lib/use-list.js
=> feat: add index to renderMini

.eslintignore, lib/render-list.js, test/__snapshots__/render-list.test.snap.js
Add part for the scroller element.
=> feat: add scroller part

cosmoz-omnitable-styles.js
Adjust scroller style in mini mode.
=> feat(mini): adjust scroller style

cosmoz-omnitable-styles.js
=> fix(omnitable): prevent double scrollbar in mini mode

lib/cosmoz-omnitable-resize-nub.js
Add the pointer event when column changes.
=> feat(resize-hub): add event when column changes

lib/settings/style.css.js
=> feat(lib/settings): restore display flex

demo/helpers/x-page.js, lib/settings/normalize.js
Remove saved setting of disabled column
[Slack](https://neovici.slack.com/archives/C6LJQMJFM/p1724832342210009)
=> fix: remove saved setting of disabled column

lib/settings/drivers/remote.js, lib/settings/use-saved-settings.js
https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/16820
=> fix: reset to factory omnitable

cosmoz-omnitable-column-autocomplete.js
Added `show-single`, `preserve-order` and `limit`.
=> feat: expose more autocomplete options

lib/settings/cosmoz-omnitable-settings.js, lib/use-footer.js, package-lock.json, package.json
BREAKING CHANGE: Update to cosmoz-dropdown with floating-ui support
=> feat: update to cosmoz-dropdown with floating-ui support

cosmoz-omnitable-header-row.js
Add part for cosmoz-omnitable-settings element.
[AB#10463](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/10463/)
=> fix: expose part for omnitable settings

cosmoz-omnitable-styles.js
Further fix aon [AB#19255](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/19255) - more vars for styiling of the omnitable checkbox
=> fix(vars): further styling vars for omnitable styling for themes

cosmoz-omnitable-header-row.js
=> fix: remove whitespaces in header

cosmoz-omnitable.js, package-lock.json, package.json
[AB#18626](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/18626)
For 9.0.0 details https://github.com/Neovici/cosmoz-bottom-bar/pull/171
=> feat(deps): bump cosmoz-bottom-bar from 8.0.0 to 9.0.3

cosmoz-omnitable.js, grouped-list/cosmoz-grouped-list-row.js, grouped-list/cosmoz-grouped-list.js, grouped-list/index.js, grouped-list/use-collapsible-items.js, grouped-list/use-cosmoz-grouped-list.js, grouped-list/use-selected-items.js, grouped-list/use-weak-state.js, grouped-list/utils.js, package-lock.json, package.json, test/grouped-list.test.js
Integrate `cosmoz-grouped-list` code in omnitable because it does not
make to keep it separate.
=> Integrate grouped list

cosmoz-omnitable-styles.js
[AB#19882](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/19882)
Quick fix. 
[Slack Thread](https://neovici.slack.com/archives/CCU2R1Q3Y/p1747220356449219?thread_ts=1742560616.796269&cid=CCU2R1Q3Y)
Before:
https://github.com/user-attachments/assets/f7ad3089-ca67-4bc0-ba2e-f85339f34afa
After:
https://github.com/user-attachments/assets/193f7755-67f2-4fac-a3c6-1fc436985a40
=> fix: bottom-bar covered in horizontal split view

cosmoz-omnitable-styles.js
Variable for cosmoz input padding for the header.
=> feat: Cosmoz input padding variable

cosmoz-omnitable-skeleton.js, cosmoz-omnitable-styles.js, cosmoz-omnitable.js, lib/compute-layout.js, lib/render-header.js, lib/render-list.js, lib/use-header.js, lib/use-list.js, lib/use-omnitable.js, test/render-list.test.js
Use a skeleton loader for omnitable instead of showing "Data set is updating" message.
[AB#15783](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/15783)
=> fix: omnitable skeleton loader

cosmoz-omnitable-styles.js, lib/render-header.js
=> feat(header): add parts and vars

lib/settings/style.css.js
Color vars for themes support.
=> feat: color variables for omnitable settings

lib/compute-layout.js, lib/utils.js
Not tested on browsers that do not support `Array.lastIndex` !
=> fix: lastIndex shim

cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-boolean.js, cosmoz-omnitable-column-list-horizontal.js, cosmoz-omnitable-column-list.js, cosmoz-omnitable.js, package-lock.json, package.json
Replace paper-spinner with cosmoz-spinner https://github.com/Neovici/cosmoz-omnitable/issues/669
=> refactor(spinner): replace paper-spinner with cosmoz-spinner

package-lock.json, package.json, web-dev-server.config.mjs
Use esbuild plugin to support typescript https://github.com/Neovici/cosmoz-omnitable/issues/693
=> feat: add ts support in dev server
