cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-autocomplete.html, cosmoz-omnitable-column-behavior.html, cosmoz-omnitable-column-boolean.html, cosmoz-omnitable-column-date-behavior.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-number.html, cosmoz-omnitable-item-row.html, demo/full-demo.html
The optimal default width does vary depending on the `editable` property.
Currently needed in column datetime.
Added properties
- cellWidth
- editCellWith
Removed property
- width
=> Allow a default column width value which is dependent on the editable property

cosmoz-omnitable.js
* Removed data.length condition
* Call `column.resetFilter` when a hash-param is `null`
fixes #83
=> Fix filtering when data is empty

cosmoz-omnitable-repeater-behavior.html, cosmoz-omnitable.html
When creating or removing elements in repeater add and remove the hidden attribute.
fixes #85
=> Add and remove hidden attribute for groupOnColumn elements

cosmoz-omnitable.js
related to #87 
When `groupOnColumn` changes in the same call stack `resetFilter` is called and hash params are updated. In the same stack than route hash params are checked and groupOn is different so it gets set to the value from hash-param.
fixes #87
=> Don't handle hash param updates while updating route params fix #87

cosmoz-omnitable-styles.html, cosmoz-omnitable.html, test/xlsx-export.html
Moved csv/xlsx buttons to extra menu in cosmoz-bottom-bar.
To be merged after https://github.com/Neovici/cosmoz-bottom-bar/pull/21
=> Moved csv/xlsx buttons to extra menu

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-number.html, cosmoz-omnitable-column-time.html, cosmoz-omnitable-styles.html, ui-helpers/cosmoz-clear-button.html
Currently needed to display the clear button in the filters-dialog (PR https://github.com/Neovici/cosmoz-omnitable/pull/90) without having to include the styles into the template.
=> Clear button element instead of iron-icon with class

test/range-date.html, test/range.html
Use `set` for `_filterInput` changes in tests.
Change order of property updates and event listeners.
=> Tests updated

cosmoz-omnitable-column-behavior.html
Handle null/undefined in `_applySingleFilter`.
It is possible for `this.get(this.valuePath, item)` to be null sometimes.
=> Handle null/undefined in _applySingleFilter

analysis.json, cosmoz-omnitable-column-behavior.html, cosmoz-omnitable-column.html, ui-helpers/cosmoz-clear-button.html
fixes https://github.com/Neovici/cosmoz-omnitable/issues/151
In cosmoz-omnitable-column the close iron-icon with hidden attribute was visible because of suffix ::slotted(*) { display: inline-block;  Used the existing ui-helper: cosmoz-clear-button fixing css for visible attribute. Added light attribute to keep the original css of iron-icon close.
=> Fix for clear buttons always visible in polymer 2

cosmoz-omnitable-column-behavior.html, test/basic.html
* Do not update `sortOn` or `groupOn` property of columns with `valuePath` if they have been set
* Added test to show issue with column's groupOn and sortOn properties
* Attempt to fix weird timeout when running tests
=> Do not override sortOn and groupOn properties on columns with valuePath when they are defined

cosmoz-omnitable-column-date-behavior.html
Check for null formatter in date columns.
Formatter can be null/undefined in 2.x when filter is set to value before the column is initialized.
=> Check for null formatter in date columns

cosmoz-omnitable-templatizer.html
Set _methodHost  to the host property to fix` method hasFilter not defined` warning.
=> Set _methodHost  to the host property

cosmoz-omnitable-column-list-behavior.html, cosmoz-omnitable-column-list-horizontal.html, cosmoz-omnitable-column-list.html
This pull request fixes the invalid hover title for cosmoz-omnitable-column-list mentioned in #179 by creating a behavior that is shared between cosmoz-omnitable-column-list and cosmoz-omnitable-column-list-horizontal.
2 approves or a merge requested, not adding plequang to the reviewers list by request.
=> cosmoz-omnitable-column-list - Hovering title is not displayed correctly, fix

cosmoz-omnitable-column-list.html
This pull request fixes the suggestions that are not correctly displayed when text property is used. Related to #179.
Tested and seems to work, 2 approves or a merge requested.
=> Column list, column list, fix for suggestions not displayed when text property is used

cosmoz-omnitable-column-list-data.html, cosmoz-omnitable-column-list.html, test/list.html
This pull request fixes the column suggestions for cosmoz-omnitable-column-list when this column is used with data arrays containing objects instead of strings as requested in #182.
Tested both in administration of roles with regular strings and list prioritized suppliers with objects, seems to work as it should with both.
2 approves or a merge requested.
=> cosmoz-omnitable-column-list - Suggestions does not work with object items, fix

cosmoz-omnitable-column-number.html, test/range.html
fixes: #176
1. Implemented Test: item with age: 46.768 and amount: 2581 should be in the filtered items when filtering from 46.76 to 46.76  Done.
2. In cosmoz-omnitable-column-number.html added getComparableValue and added the check for minimumFractionDigits. Value is truncated to the specified decimals (2 in the test). Done.
3. Rebased on latest changes from master. Done.
4. Replaced minimumFractionDigits with maximumFractionDigits in column and range test. Done.
5. Implement Test: If we filter out values between 46,75 - 46,76, we shouldn't show a value with 46,768 since it's outside the range. Done.
6. restore toFixed to round up instead of truncate to n digits. Done.
7. Implement test: But we should show 46,75xx. Done.
8. Verify if: However, if 46,768 is displayed as 46,76 then that's …
=> Number getComparableValue with maximumFractionDigits tests, fix.

test/xlsx-export.html
Chromium 69 and later have added a space between the currency
symbol and the amount.
This commit adjusts the test accordingly since Travis uses v69.
Will fail on older Chromium up to 68.
=> Update xlsx tests for Romanian RON currency rendering

cosmoz-omnitable-column-autocomplete.html
Repeated filter broke when empty values existed in the data.
=> Added null check for empty values when in _applyMultiFilter

cosmoz-omnitable-column-behavior.html, cosmoz-omnitable.js
When a column is configured for external values, the list of local
values are not updated. Also when the column is "unconfigured" for
external values, it doesn't repopulate the local values.
This PR enables columns to send an event, requesting a new list of
values from the Omnitable "mother", hopefully making the user
experience nicer.
This seemed to be triggered in ways also where omnitable initially is
configured for externalValues but updated to reflect that it, in fact,
should not be after BE response. Causing columns to have no values at all.
There might be a significant performance impact of this if views are
flipping between externalValues and not for all columns, multiple times
in a short timeframe or there a significant amount of rows loaded when
flipping it to false. But it …
=> Repopulate values for a column when external-values gets disabled

wct.conf.json
[REVERT ME] Disable Firefox testing.
Disabling Firefox since selenium-standalone uses an outdated geckodriver which breaks tests.
As requested by @nomego.
=> [REVERT ME] Disable Firefox testing

cosmoz-omnitable-styles.html
Adding item row border bottom style.
Testing: Check that item rows has the regular bottom border. Try to set the different style for the bottom bar like:
```
cosmoz-omnitable {
--cosmoz-omnitable-item-row-border-bottom-style: none;
}
```
Requested in issue #20454.
=> 20454 - Adding item row border bottom style

cosmoz-omnitable-column-list.html, test/list.html
- drop unnecessary transformation through selected items vs filter
-- makes filterChanged handler unnecessary
--- makes filterChanged test unnecessary
-- improves data flow (shorter, one-way, keeps original objects)
- reuse unique array filtering logic from autocomplete
-- avoids inner loop
Prepares list to be aligned with autocomplete.
Testing made easier after merging #250 250
=> list column - refactor data flow

cosmoz-omnitable-column-list-horizontal.html, cosmoz-omnitable-column-list-mixin.html
Checks for set textProperty in horizontal list column. If so, uses that value instead for csv string. 
Possible test candidate is order 22679_30_7365563740132_F , saving orderrows as csv. should be the text values instead of "Object Object" .
refs RM #21223
*edit*
Did the same for "save as xlsx".
=> saving csv created faulty content with horizontal list columns

cosmoz-omnitable-column-list-horizontal.html, cosmoz-omnitable-column-list-mixin.html, cosmoz-omnitable-column-list.html
Should fix save as csv and xlsv in cosmoz-omnitable-column-list as well and not only cosmoz-omnitable-column-list-horizontal.
While trying more thoroughly testing in the many views, I discovered errors that needed to be fixed inside the views.
Created Pr https://github.com/Neovici/cosmoz-frontend/pull/1149 for this
=> Fixed extend order and moved toXlsvValue to Mixin both extends from

bower.json, cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-list-data.html, cosmoz-omnitable-column-list-horizontal.html, cosmoz-omnitable-column-list.html, cosmoz-omnitable-column-number.html, cosmoz-omnitable-column-time.html, cosmoz-omnitable.js
Component, replacing translation behavior with mixin, upgrading cosmoz-i18next component.
Component upgrade was needed to get the mixin.
Testing, run `yarn install yarn start`, go to the demo.
=> Component, replacing translation behavior with mixin, upgrading cosmoz-i18next component

cosmoz-omnitable-column-amount.html, cosmoz-omnitable-column-date.html, cosmoz-omnitable-column-datetime.html, cosmoz-omnitable-column-list-data.html, cosmoz-omnitable-column-list-horizontal.html, cosmoz-omnitable-column-list.html, cosmoz-omnitable-column-number.html, cosmoz-omnitable-column-time.html, cosmoz-omnitable.js, ui-helpers/cosmoz-clear-button.html
Components, UI-helpers, adding mixin definitions, converting UI-helpers to class-style.
Testing: 'yarn install; yarn start`, add `demo/` to the address, use a demo with a date column or any other column that uses round clear buttons, enter a value in the column filter, then use the clear button.
=> Components, UI-helpers, adding mixin definitions, converting UI-helpers to class-style

analysis.json, bower.json, cosmoz-omnitable-column-list-data.html, cosmoz-omnitable.js, demo/helpers/x-page.html
Components, Demo, converting to class-style.
This also:
- Fixes a behavior is null warning in the console. 
- Adds some testing errors that are hard to avoid in the current code state.
Testing, `yarn install; yarn start`, add `demo/` to the address.
=> Components, Demo, converting to class-style

cosmoz-omnitable-column-date-mixin.js
Allow column-item-changed event to dispatch when the date on editable date row is null (aka removed)
Needed for a period admin view that is not a PR yet.
=> Dispatch column-item-changed event when editable date is removed

cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-list.js, cosmoz-omnitable-column-mixin.js
Column list, adding omnitable search.
Testing, use together with the `rm21885-1` branch on frontend and in the Articles, Article aliases view check the Invoice article numbers column.
Tests may have to be added, but putting it here in case someone wants it now.
Issue is Redmine #21885.
=> Column list, adding omnitable search

cosmoz-omnitable-column-list-data.js
Column list, removing item bullets padding.
Note: This only works with columns *without* a `cz-link-list` since that component has it's own lists. But this is also the expected usage according to the issue #21885 where no links will be displayed.
Testing, on a `cosmoz-omnitable-column-list` check that the column list does not show padding to the left of each item.
Testing in frontend, go to Administration, List available roles and check that the function lists in the Functions column does not have padding on the left of each item.
Redmine issue is #21885.
=> Column list, removing item bullets padding

cosmoz-omnitable-column-mixin.js
No issue, was discovered by Fredrik B. and communicated via Slack. 
When list column was used with objects, that could have several values, filter broke. 
What this fix does is that it checks for if the object is in an array and flattens things in this case.
=> fix for bug with list column norefs

cosmoz-omnitable.js
After much debugging, I finally figured it out. It seems that when the omnitable is constructed, it first reads the column configuration, then it computes the visible columns and only after that it reads the hash params. The problem is that setting `visibleColumns` triggers the instantiation of the columns' header templates, which in turn causes a `cosmoz-column-filter-changed` event to be dispatched. This causes the omnitable to serialize the current filters and update the hash. The filter serialization checks if the current filters match the hash filters and synchronizes the data. It just so happens that at this moment in time, the omnitable initialization process has not finished and the hash params were not yet read. This mismatch between the hash and the current filters (which are …
=> fix: filters are lost after refresh

cosmoz-omnitable-column-amount.js, cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-date.js, cosmoz-omnitable-column-datetime.js, cosmoz-omnitable-column-list-horizontal.js, cosmoz-omnitable-column-list.js, cosmoz-omnitable-column-number.js, cosmoz-omnitable-column-time.js, cosmoz-omnitable-styles.js
To indicate whether the suggestions come from the loaded list
or elsewhere.
=> fix: enable styling of local/remote column header suggestions

cosmoz-omnitable-column-autocomplete.js
Remaps `values` from object to array if not passed an array.
=> feat: allow objects as autocomplete values

cosmoz-omnitable-column-autocomplete.js
Restores older autocomplete behavior where the text or tests in the columns are used for sorting and grouping (comparable value).
=> fix: autocomplete string comparable value

cosmoz-omnitable-column-number.js
Check that header dropdown menus does not show an arrow down icon right of the texts.
Redmine 22545.
=> fix: hide dropdown menu icons #22545

cosmoz-omnitable-column-list-data.js
Ellipses did not show up with list data columns.
From issue: https://github.com/Neovici/cosmoz-omnitable/issues/378
=> fix(column-list-data): add ellipses to overflow

cosmoz-omnitable-column-list-mixin.js, test/autocomplete.test.js
To fix the issue with key names (key/value, id/label, value/text)
in object items, and optimize network payload size, suggestions
could be supplied as a key/value object.
It also automatically handles uniqueness.
We have some scenarios today where this happens and should move
more towards it. This enables support "natively" in omnitable
and allows us to drop enrichers/mappers.
=> feat: autocomplete: allow key/value object suggestions source

cosmoz-omnitable-column-autocomplete.js
Check that the `cosmoz-omnitable-column-autocomplete` only shows the loading spinner animation when loading, otherwise the area should not be occupied.
RM:24260.
=> fix: autocomplete, only render spinner when loading #24260

cosmoz-omnitable-column-list.js
Check that the `cosmoz-omnitable-column-list` only shows the loading spinner animation when loading, otherwise the area should not be occupied.
For example the Assigned to... column in Open invoices in frontend.
RM:24260.
=> fix: list, only render spinner when loading #24260

cosmoz-omnitable.js, package-lock.json, package.json, shell.nix
Replaces `iron-resizable-behavior` with a `ResizeObserver`.
Should provide a small performance increase.
fixes #387
=> fix: replace iron-resizable-behavior with a ResizeObserver

cosmoz-omnitable.js
If the data has changed when the omnitable is not visible, then the list continues to render the old items (iron-list bails rendering if it's not visible).
Fixes #24702 (RM:24702)
=> fix(render): grouped list renders old items

cosmoz-omnitable.js, test/basic.test.js
Broken in https://github.com/Neovici/cosmoz-omnitable/pull/388: by dropping the use of `mixinBehaviors`, it inadvertently removed the arrayDelete method. `mixinBehaviors` applies Polymer's `LegacyElementMixin` under the hood, which includes the arrayDelete method.
Re https://github.com/Neovici/cosmoz-frontend/pull/2804
=> fix(removeItem): arrayDelete is undefined

cosmoz-omnitable.js, shell.nix
Don't depend on hasActions from cosmoz-bottom-bar anymore since it does not
make sense to have a omnitable without selection.
=> fix: always selectable if data is valid

cosmoz-omnitable-column-list-mixin.js
handles null values in list columns.
`typeof null` -> `"object"`
=> fix: handles null values in list columns

cosmoz-omnitable.js, package-lock.json, package.json
Includes https://github.com/Neovici/cosmoz-bottom-bar/pull/89 breaking change.
BREAKING CHANGE: If your component allows adding content to the omnitable via the actions slot,
then you have to also make sure you also export `bottom-bar-toolbar` and `bottom-bar-menu`,
otherwise the actions will not show up.
Re #24802 (RM:24802)
TODO:
=> fix: upgrade to latest bottom-bar

cosmoz-omnitable-column-boolean.js
When clearing the boolean value `filter` is set to `undefined`.
That does not actually notify about the update (clearing the value) so we have to set the `filter` to null.
=> fix(column-boolean): notify when clearing

cosmoz-omnitable-styles.js
If initialized in a hidden tab or somehow not visible at create
the cosmoz-omnitable element will scroll internally because of the overflow
of its cosmoz-bottom-bar element
This sets overflow: hidden on the bar preventing the bug.
=> fix(bar): overflow bar to prevent auto scrolling

cosmoz-omnitable-column-autocomplete.js
Updated the `getComparableValue` fn in `autocomplete` column to handle textProperty and valueProperty.
If the cell value is not an array it returns the value as it is.
Because of that numeric sort should just work.
Fixes #408  but doesn't need to add the attribute.
=> fix(column-autocomplete): handle numbers in getComparableValue

cosmoz-omnitable.js, test/basic.test.js
Adds a `totalAvailable` property that is used to render the total available
number of items if greater than current data.
#230
=> feat(cosmoz-omnitable): renders totalAvailable in row stats

lib/layout.js, lib/use-fast-layout.js, test/layout.test.js
In certain situations, columns are not hidden correctly, when the table is grouped. 
Fixes #437
=> fix(layout): layout is broken when grouping

.github/workflows/workflow.yml, cosmoz-omnitable.js, lib/use-fast-layout.js
Caught during integration with Cosmoz frontend. When navigating a cosmoz-data-nav, the omnitables that are rendered off-screen do not properly render the list. The <iron-list> skips rendering if it is not connected.
=> Fix render issue in cosmoz-data-nav

cosmoz-omnitable-column-amount.js, cosmoz-omnitable-column-autocomplete.js, cosmoz-omnitable-column-date.js, cosmoz-omnitable-column-datetime.js, cosmoz-omnitable-column-list-mixin.js, cosmoz-omnitable-column-mixin.js, cosmoz-omnitable-column-number.js, cosmoz-omnitable-column-time.js, lib/use-processed-items.js, lib/utils-amount.js, lib/utils-date.js, lib/utils-number.js, lib/utils-time.js, test/autocomplete.test.js, test/range-amount.test.js, test/range-date.test.js, test/range-time.test.js, test/range.test.js
The signature getComparableValue(item, valuePath, column) sticks out like a sore thumb. I refactored the function so it matches the other required functions, which use f(column, item).
BREAKING CHANGE: the signature is now getComparableValue(column, item)
=> Refactor getComparableValue

lib/use-processed-items.js
This fixes the filters not displaying suggestions bug.
=> fix(legacy-interop): match polymer property change events

README.md, lib/normalize-settings.js, lib/use-dom-columns.js, lib/use-fast-layout.js, lib/use-omnitable.js, lib/use-processed-items.js, lib/use-resizable-columns.js, lib/utils-data.js, test/basic.test.js, test/boolean.test.js, test/integration/templatize.test.js, test/list.test.js, test/range-amount.test.js, test/range-date.test.js, test/range-time.test.js, test/range.test.js
The bug is caused by a stale reference to the column config
object, which causes the `values` property to always be
undefined after normalizing columns. Use of
`[columnSymbol]` is confusing. It turns out that
`[columnSymbol]` was repurposed during the development of
useDOMColumns, but it actually makes more sense to keep the
new usage and drop the old one. Refactored accordingly.
Fixes https://neovici.slack.com/archives/C6LJQMJFM/p1639645068158300?thread_ts=1639645019.158200&cid=C6LJQMJFM
=> fix: external values stops working after column resize

cosmoz-omnitable-column.js
Use null for filter reset so that Polymer trigger change notifications correctly.
=> fix: use null for filter reset

cosmoz-omnitable-column-mixin.js, cosmoz-omnitable-column.js, lib/use-omnitable.js, lib/use-processed-items.js
There are places where the app sets the `filter` value directly on the column. This used to work.
To make this work again, I have added some compatibility code that updates the internal filter
state when the filter prop is set by third-party code.
Fixes https://neovici.slack.com/archives/CCU2R1Q3Y/p1642752170065000
Fixes RM:27755
=> fix(legacy): column.filter to internal state mapping

cosmoz-omnitable-column-list-mixin.js, lib/use-hash-state.js, test/hash-param-write.test.js
Removes the double encoding of filter params.
=> fix(use-hash-state): remove double encoding

cosmoz-omnitable.js, lib/use-omnitable.js, lib/use-sort-and-group-options.js, package-lock.json, package.json
Uses the `descending` and `groupByDescending` defined on the host when
the hash param are empty.
=> fix(sort-and-group-options):  fallback descending/groupByDescending

lib/cosmoz-omnitable-group.js
Correctly persists groupOn selection by using the `groupOn` property
from the context.
=> fix(groupOn): persists selection

cosmoz-omnitable.js
Fire item click when clicking on row but not on a link, checkbox or the
expand button
=> fix(omnitable): improve item click

lib/settings/cosmoz-omnitable-settings.js, lib/settings/style.css.js
On ios the close button must be focused and then blurred to close
omnitable settings
Fixes also small layout inconsistencies.
=> fix(settings): close button in ios

lib/settings/use-settings-ui.js
Safari iOS requires setting some `text/plain` data in the dataTransfer to allow native HTML5 drag and drop.
=> fix(settings): drag and drop columns on ios

lib/settings/drivers/context.js, lib/settings/drivers/index.js, lib/settings/drivers/local.js, lib/settings/drivers/remote.js, lib/settings/use-saved-settings.js
Allow passing different omnitable settings drivers via context.
Adds 2 drivers:
1. local  - saves and reads data from localStorage
2. remote - save and reads data via get$ & post$ fns
=> feat(settings): initial settings drivers support

lib/settings/use-settings.js
An error occurs when columns with custom settings (size, order, etc) are dropped from the columns list.
Fixes https://neovici.slack.com/archives/C6LJQMJFM/p1664996455187809?thread_ts=1664913886.064969&cid=C6LJQMJFM
=> fix(use-settings): error when removing columns

cosmoz-omnitable.js, test/hash-param-read.test.js
This breaks Polymer views using two-way data-binding to read selectedItems.
Fixes https://neovici.slack.com/archives/C0515MVB8/p1666854100493349
=> fix: selected-items-changed is sent too late

cosmoz-omnitable.js, test/basic.test.js, test/hash-param-read.test.js
We don't need to notify sort/descending on init.
=> feat: don't init notify sort/descending

cosmoz-omnitable.js, lib/polymer-haunted-render-mixin.js
Fix CSS not having Shaddy css shim applied.
Note: We should replace most Polymer components and drop the shim requirements.
Without it  content is not properly styled in some cases.
=> fix(styles): shim styles

cosmoz-omnitable-styles.js
Re [AB#9162](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/9162) - Follow-up of a previous [pull request](https://github.com/Neovici/cosmoz-omnitable/pull/564)- the styling settings in the omnitable folder are reset to previous defaults, but they are made modifiable with the usage of CSS vars.
The screenshot shows the desired outcome:
=> CSS Vars reset in Omnitable Header styling

cosmoz-omnitable-column-mixin.js, lib/use-dom-columns.js, lib/use-processed-items.js
Per column `noLocalFilter`.
When enabled the column will not filter items.
=> feat(noLocalFilter): per column noLocalFilter

cosmoz-omnitable-styles.js
Follow up on a previous [PR](https://github.com/Neovici/cosmoz-omnitable/pull/581) about the Feat [AB#9329](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/9329)
=> fix: links in omnitable underlined only on hover

lib/use-dom-columns.js
Uses valuePath that fallbacks to name for sortOn & groupOn.
=> fix(lib/use-dom-columns): fallback sortOn, groupOn on valuePath

lib/utils-date.js
Encountered error when trying to export xlsx with 1/1/1 dates.
=> fix(xlsx): error when date is malformed

lib/use-list.js
So we can hide them if required.
=> feat: export checkboxes as parts

cosmoz-omnitable-column-list-data.js, cosmoz-omnitable-column-list.js, cosmoz-omnitable-item-expand.js, lib/use-list.js, lib/utils.js, package-lock.json, package.json, test/autocomplete.test.js, test/basic.test.js, test/boolean.test.js, test/expand-line.test.js, test/group.test.js, test/hash-param-read.test.js, test/hash-param-write.test.js, test/helpers/utils.js, test/list.test.js, test/range-amount.test.js, test/range-date.test.js, test/range-datetime.test.js, test/range-time.test.js, test/range.test.js, test/select.test.js, test/xlsx-export.test.js
Re https://neovici.slack.com/archives/C6LJQMJFM/p1709065934200789
=> feat: upgrade cosmoz-grouped-list

package-lock.json, package.json
About Feature [AB#11519](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/11519) - latest cosmoz-input release (v5.0.0) needs to be installed in all the components using it.
=> fix(dependencies): new inputs needed in all their instances

cosmoz-omnitable-styles.js
About [AB#11519](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/11519) - `--cosmoz-input-padding` set to a value different from 0 on header would cause misalignments. This change resets the horizontal alignment.
=> fix(input-padding): spacing in the omnitable header horizontally aligned

cosmoz-omnitable-column-mixin.js, cosmoz-omnitable-item-expand-line.js, cosmoz-omnitable-item-expand.js, cosmoz-omnitable-item-row.js, cosmoz-omnitable-styles.js, cosmoz-omnitable.js, lib/settings/style.css.js, lib/use-canvas-width.js, lib/use-dom-columns.js, lib/use-fast-layout.js, lib/use-layout.js, lib/use-list.js, lib/use-mini.js, lib/use-omnitable.js, lib/use-resizable-columns.js, lib/use-track-size.js
Implement the `mini` mode for omnitable.
To activate it 2 things are required
1. omnitable width below `mini-breakpoint` - defaults to 480px
2. the `mini` attribute/property on any enabled column
The mini attribute can also be used to set the order of the columns like in a flex layout. 
The first column with the mini attribute will be the main column in the mini layout. The other ones will be rendered below.
Developers can additionally control the render of a mini column using `renderMini` property
=> Implement mini layout

.husky/commit-msg, lib/settings/use-settings.js, lib/use-dom-columns.js, lib/use-fast-layout.js, package-lock.json, package.json, test/basic.test.js
Recompute css when columns change.
Debounce to animationFrame the collection of columns from the DOM.
=> Recompute css when columns change

cosmoz-omnitable-header-row.js, cosmoz-omnitable-item-row.js
Expose more header & itemRow  cell parts.
=> feat(styling): expose more parts

lib/use-mini.js
Check for null and undefined mini attribute when checking if a column is
enabled in mini mode.
=> fix(mini): check for null and undefined mini attribute

cosmoz-omnitable-column-boolean.js
Make sure cosmoz-listbox is rendered when user clicks chip of cosmoz-autocomplete-column-boolean
[AB#16384](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/16384/)
=> fix(cosmoz-omnitable-column-boolean): make listbox render when clicking boolean chip

cosmoz-omnitable-column-date.js, cosmoz-omnitable-styles.js, lib/cosmoz-omnitable-number-range-input.js
Omnitable title align to the right and use font-variant-numeric for date
[AB#17293](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/17293/)
=> fix(lib): title align to the right + use font-variant-numeric

lib/use-sort-and-group-options.js
Pipe `initial` value thru `read` to make sure we encode it correctly.
=> fix: boolean initial descending and groupDescending

lib/render-footer.js, lib/use-fast-layout.js, lib/use-footer.js, lib/use-mini.js, lib/use-omnitable.js
Set max-toolbar-items on cosmoz-bottom-bar when mini table is used
[AB#17737](https://dev.azure.com/neovici/Cosmoz3/_backlogs/backlog/UX/Stories/?workitem=17737)
=> fix(footer): set max-toolbar-items when mini table is used

lib/use-omnitable.js, lib/use-public-interface.js
Emit event with useNotifyProperty for when mini table is used.
[AB#17737](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/17737/)
=> fix: emit event for when mini table is used

lib/render-footer.js, lib/use-footer.js, lib/use-omnitable.js
Remove unused logic for setting max toolbar items, controlling this from cosmoz-bottom-bar instead ([PR#166](https://github.com/Neovici/cosmoz-bottom-bar/pull/166))
[AB#17737](https://dev.azure.com/neovici/Cosmoz3/_backlogs/backlog/UX/Stories/?workitem=17737)
=> fix(footer): remove unused logic for setting max toolbar items

cosmoz-omnitable-styles.js
Feat [AB#19255](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/19255) - styling variables in omnitable to allow conditional styling in frontend. Main use case will be the distinction between dark and light theme
=> fix(css): styling of omnitable accessible from outside via vars

lib/use-fast-layout.js, lib/use-tween-array.js
The animation triggers a new render on each frame, because of the use of `useState`. Refactored to use only meta references so it does not trigger renders.
=> fix: optimize layout animation
